--SQL> @C:\Users\melvi\SQL_Projects\Medical_Hospital\Medical_Hospital_Database_Creation.txt

--//////////////////////////////////////////////////////////////
--Loading Medical Hospital Database Tables:
--	H_STAFF
--	H_DEPARTMENTS
--	H_PATIENTS
--	H_APPOINTMENTS
--	H_MEDICINE  
--//////////////////////////////////////////////////////////////

--Creating H_STAFF table
CREATE TABLE H_STAFF
(
FIRST_NAME		VARCHAR(25) NOT NULL,
MIDINIT			CHAR,
LAST_NAME		VARCHAR(25) NOT NULL,
SSN			NUMBER(9)   NOT NULL,
BDATE 			DATE	    NOT NULL,
ADDRESS 		VARCHAR(40) NOT NULL,
SEX 			CHAR(25),
SALARY 			NUMBER(9)   NOT NULL,
SUPERSSN 		NUMBER(9),
DNUM 			NUMBER(10)  NOT NULL,
POSITION		VARCHAR(15) NOT NULL,
WORKER_NUM		NUMBER(9));

ALTER TABLE H_STAFF
ADD CONSTRAINT PK_H_STAFF
PRIMARY KEY(WORKER_NUM);
COMMIT;

CREATE SEQUENCE SEQ_WORKER_NUM
START WITH 16
INCREMENT BY 1;
COMMIT;

--//////////////////////////////////////////////////////////////

--Creating H_DEPARTMENTS table
CREATE TABLE H_DEPARTMENTS
(
DEPT_NAME		VARCHAR(30) NOT NULL,
DEPT_CODE		NUMBER(10),
DEPT_WING		VARCHAR(30) NOT NULL,
DEPT_MGR		NUMBER(9)   NOT NULL);

ALTER TABLE H_DEPARTMENTS
ADD CONSTRAINT PK_H_DEPARTMENTS
PRIMARY KEY(DEPT_CODE);
COMMIT;

CREATE SEQUENCE SEQ_DEPT_CODE
START WITH 6
INCREMENT BY 1;

COMMIT;

--//////////////////////////////////////////////////////////////

--Creating H_PATIENTS table
CREATE TABLE H_PATIENTS 
(
FIRST_NAME		VARCHAR(25) NOT NULL,
MIDINIT			CHAR,
LAST_NAME		VARCHAR(25) NOT NULL,
SSN			NUMBER(9)   NOT NULL,
BDATE 			DATE	    NOT NULL,
ADDRESS 		VARCHAR(40) NOT NULL,
SEX 			CHAR(10),
PATIENTS_MEDICINES_NUM	NUMBER(9)   NOT NULL,
ASSIGN_WORKERS_NUM	NUMBER(9)   NOT NULL,
PATIENT_NUM		NUMBER(9)   NOT NULL);

ALTER TABLE H_PATIENTS 
ADD CONSTRAINT PK_H_PATIENTS 
PRIMARY KEY(PATIENT_NUM);
COMMIT;

CREATE SEQUENCE SEQ_PATIENT_NUM
START WITH 11
INCREMENT BY 1;

COMMIT;

--//////////////////////////////////////////////////////////////

--Creating H_APPOINTMENTS table

CREATE TABLE H_APPOINTMENTS 
(
PATIENTS_NUM	NUMBER(9)   NOT NULL,
APPOINT_DATE	DATE	      NOT NULL,
APPOINT_TIME	VARCHAR(15)	NOT NULL,
APPOINT_NUM	NUMBER(9));

ALTER TABLE H_APPOINTMENTS 
ADD CONSTRAINT PK_H_APPOINTMENTS 
PRIMARY KEY(APPOINT_NUM);
COMMIT;


CREATE SEQUENCE SEQ_APPOINT_NUM
START WITH 11
INCREMENT BY 1;

COMMIT;

--//////////////////////////////////////////////////////////////

--Creating H_MEDICINE table

CREATE TABLE H_MEDICINE
(
MEDICINE_NUM	NUMBER(8),
MEDICINE_NAME	VARCHAR(40) NOT NULL,
MEDICINE_PRICE	NUMBER(6,2) NOT NULL,
EXP_DATE	DATE	    NOT NULL);

ALTER TABLE H_MEDICINE 
ADD CONSTRAINT PK_H_MEDICINE
PRIMARY KEY(MEDICINE_NUM);
COMMIT;

CREATE SEQUENCE SEQ_MEDICINE_NUM
START WITH 6
INCREMENT BY 1;

COMMIT;

--//////////////////////////////////////////////////////////////

--Creating H_RECORDS table
CREATE TABLE H_RECORDS
(
RECORD_NUM	  NUMBER(8),
PATIENTS_NUM	  NUMBER(9)   NOT NULL,
PATIENTS_HEIGHT	  VARCHAR(10)  NOT NULL,
PATIENTS_WEIGHT   VARCHAR(6)   NOT NULL,
PATIENT_DISEASES  VARCHAR(70),
EMERGENCY_CONTACT VARCHAR(14)  NOT NULL);

ALTER TABLE H_RECORDS 
ADD CONSTRAINT PK_H_RECORDS
PRIMARY KEY(RECORD_NUM);
COMMIT;


CREATE SEQUENCE SEQ_RECORD_NUM
START WITH 11
INCREMENT BY 1;
COMMIT;

--//////////////////////////////////////////////////////////////

--Creating Unique keys constraints

ALTER TABLE H_STAFF
ADD CONSTRAINT UNIQ_H_STAFF_SSN
	UNIQUE(SSN);
COMMIT;

ALTER TABLE H_PATIENTS 
ADD CONSTRAINT UNIQ_H_PATIENTS_SSN
	UNIQUE(SSN);
COMMIT;

ALTER TABLE H_DEPARTMENTS
ADD CONSTRAINT UNIQ_H_DEPARTMENTS_WING
	UNIQUE(DEPT_WING);
COMMIT;


--//////////////////////////////////////////////////////////////

--Creating foreign keys constraints

--H_STAFF
ALTER TABLE H_STAFF
ADD CONSTRAINT FK_H_STAFF_SUPERSSN
FOREIGN KEY(SUPERSSN) 
	REFERENCES H_STAFF(SSN);

ALTER TABLE H_STAFF
ADD CONSTRAINT FK_H_STAFF_DNUM
FOREIGN KEY(DNUM)
	REFERENCES H_DEPARTMENTS(DEPT_CODE);

--//////////////////////////////////////////////////////////////

--	H_DEPARTMENTS
ALTER TABLE H_DEPARTMENTS
ADD CONSTRAINT FK_H_DEPARTMENTS_MGR_SSN
FOREIGN KEY(DEPT_MGR)
	REFERENCES H_STAFF(SSN);

--//////////////////////////////////////////////////////////////

--	H_PATIENTS
ALTER TABLE H_PATIENTS
ADD CONSTRAINT FK_H_PATIENTS_MEDICINE
FOREIGN KEY(PATIENTS_MEDICINES_NUM)
	REFERENCES H_MEDICINE(MEDICINE_NUM);

ALTER TABLE H_PATIENTS
ADD CONSTRAINT FK_H_PATIENTS_WORKER
FOREIGN KEY(ASSIGN_WORKERS_NUM)
	REFERENCES H_STAFF(WORKER_NUM);

--//////////////////////////////////////////////////////////////

--	H_APPOINTMENTS
ALTER TABLE H_APPOINTMENTS
ADD CONSTRAINT FK_H_APPOINTMENTS_PATIENTS_NUM
FOREIGN KEY(PATIENTS_NUM)
	REFERENCES H_PATIENTS(PATIENT_NUM);

--//////////////////////////////////////////////////////////////

--	H_RECORDS
ALTER TABLE H_RECORDS
ADD CONSTRAINT FK_H_RECORDS_PATIENTS_NUM
FOREIGN KEY(PATIENTS_NUM)
	REFERENCES H_PATIENTS(PATIENT_NUM);

COMMIT;

--//////////////////////////////////////////////////////////////


