

DROP TABLE H_STAFF CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_WORKER_NUM;

DROP TABLE H_DEPARTMENTS CASCADE CONSTRAINTS; 
DROP SEQUENCE SEQ_DEPT_CODE;

DROP TABLE H_PATIENTS  CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PATIENT_NUM;

DROP TABLE H_APPOINTMENTS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_APPOINT_NUM;

DROP TABLE H_MEDICINE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_MEDICINE_NUM;

DROP TABLE H_RECORDS CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_RECORD_NUM;
